### ISSUE TITLE
CRDs out of date

### ISSUE THREAD

**Issue by g0dsCookie** [tg123/sshpiper-chart#5]
Hi,

the [CRDs](https://github.com/tg123/sshpiper-chart/blob/main/charts/sshpiper/crds/crd.yaml) in this chart are not up to date with the current [sshpiper version](https://github.com/tg123/sshpiper/blob/v1.2.8/plugin/kubernetes/crd.yaml) and are missing some properties like Pipe.spec.from.htpasswd_data or .htpasswd_file.

**Comment by tg123** [comment]
thanks fixed in 0.4.1
